// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBR1Vc5DuTukvf4cNwA3eiF_j3m7gMmlQk',
    appId: '1:712647260024:web:5aaf659571ed67934a7a8d',
    messagingSenderId: '712647260024',
    projectId: 'ecosaver-60ef6',
    authDomain: 'ecosaver-60ef6.firebaseapp.com',
    storageBucket: 'ecosaver-60ef6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4d032FFtzTqqThWpmUHp0aHM29KExQgw',
    appId: '1:712647260024:android:bec3ac2dba2588ca4a7a8d',
    messagingSenderId: '712647260024',
    projectId: 'ecosaver-60ef6',
    storageBucket: 'ecosaver-60ef6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnrXD2cobeQUBp89g1sKH5rbqzL6_yDfo',
    appId: '1:712647260024:ios:4037d99a390c71dd4a7a8d',
    messagingSenderId: '712647260024',
    projectId: 'ecosaver-60ef6',
    storageBucket: 'ecosaver-60ef6.appspot.com',
    iosClientId: '712647260024-f14n55usv09dnrav7ncjansb9mm4dr15.apps.googleusercontent.com',
    iosBundleId: 'com.dileepalbj.trashpick',
  );
}
